### ISSUE TITLE
Basic configuration

### ISSUE THREAD

**Issue by certainty** [certainty/graphqshell#18]
## Depends on

- #19 

## Summary

As a user I want to be able to permanently configure important aspects of the application.
The following lays out the configuration that I want to start with.

```
// endpoints 
endpoint:
  default: True // will be the default 
   url: foo.bar
   custom-headers: 
       name: value 
   Link: ... // underlying link when displayed 

// Theme config:
themes:
   Name: foo 
   Path: path to theme file 
```
