### ISSUE TITLE
Add command line switch to select endpoint

### ISSUE THREAD

**Issue by certainty** [certainty/graphqshell#26]
Width the configuration in place, you can now define multiple endpoints. The one marked as default will be used by default.
However a user might want to temporarily override this default and specify the endpoint to use from the config instead.

Introduce a new command line switch to allow that.

```
graphqshell-exe -e my_test_endpoint
```
Now consider the following config
```yaml
endpoints
  - name: my_test_endpoint
    url: http://example.com/graphql
    default: false
  - name: the_default
     url: http://example.com/foo
     default: true
```

### Acceptance criteria

- [ ] the endpoint can be specified by name on the command line
- [ ] if the name is specified and it exists in the config it is used to connect to
- [ ] if the name is specified and it doesn't exist in config it is an error
